version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: bunny-rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    environment:
      RABBITMQ_DEFAULT_USER: "bunny"
      RABBITMQ_DEFAULT_PASS: "carrot123"
      RABBITMQ_DEFAULT_VHOST: "/"
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbit log_levels [{connection,error},{default,error}]"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./definitions.json:/etc/rabbitmq/definitions.json:ro
    networks:
      - bunny-network

networks:
  bunny-network:
    driver: bridge
    name: bunny-network

volumes:
  rabbitmq_data:
    driver: local
    name: bunny-rabbitmq-data